### ISSUE TITLE
Enhancing readme.md file

### ISSUE THREAD

**Issue by neeru24** [prrockzed/nvimDev#10]
Hi,

I’ve been exploring the project and appreciate the work you’ve done so far. I’d like to propose an update to the README.md file to provide a more comprehensive overview of the website. Here are a few ideas I have in mind:

We can add emojis, proper spacing and animations to make it more readable and engaging 

I believe these updates could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.

I’m committed to continually improving the quality of our documentation.

Thank you!

**Comment by prrockzed** [comment]
Exactly what kind of proper spacing and animations are you talking about. Please explain in detail: if you have a photo of your animation, at what line numbers the spacing isn't proper etc.

**Comment by neeru24** [comment]
> Exactly what kind of proper spacing and animations are you talking about. Please explain in detail: if you have a photo of your animation, at what line numbers the spacing isn't proper etc.

![Uploading Screenshot_2024-10-07-08-22-44-041_com.github.android.jpg …]()

![Screenshot_2024-10-07-08-23-00-873_com.github.android.jpg](https://github.com/user-attachments/assets/ae449477-3ec9-4098-b501-43f5d771e56a)

I noticed that the 'Getting Started' section in the README could be broken down into clear, step-by-step instructions to make it easier for users to follow.

Right now, it's a bit challenging to understand when presented in paragraph form. 

Additionally, the introduction could be improved to provide more clarity, and to make the page more engaging, a typing SVG animation could be added at the beginning to grab attention and make it visually appealing.

**Comment by prrockzed** [comment]
Thanks Neeru for all the suggestions. But right now, i don't think that the readme needs any more attention.

As for the 'Getting Started' section, it isn't the installation process which should be broken down into step by step instructions. There is no particular order(to make it step by step) in which you can formulate the readme. Its just the nature of 'Getting Started' section, and i have already highlighted all the keywords to make it easier to follow. Like it has Wiki Section, Release Notes, Guide to Getting Started and Discussion forum. You can't order these topics to make a it step by step instruction.

Also if you have gone through any serious projects in github, none of them have an animation(whether typing or anything else) to begin with. Hence, i am not keeping any animations in my project.

If you can contribute in any way else, i will be more than happy to guide you.
