### ISSUE TITLE
 Enhanced File Navigation with Fuzzy Finder

### ISSUE THREAD

**Issue by sv410** [prrockzed/nvimDev#15]
Benefit:
This feature streamlines the file navigation process, making it faster and more intuitive. Users can quickly locate and open files, enhancing their coding efficiency.

Is your feature request related to a plugin? Want to add a new plugin?
Name of the plugin: fzf.nvim

Description: fzf.nvim is a fuzzy finder for Neovim that allows users to search and open files quickly by typing part of the filename. It enhances the file navigation experience, making it easier to locate files in larger projects.

Link to the plugin configuration: [fzf.nvim GitHub Repository](https://github.com/junegunn/fzf)
s your feature request related to a problem? Please describe.
Description of the problem: I'm always frustrated when navigating through large projects with numerous files. It can be time-consuming and cumbersome to find specific files or navigate through directories manually.

Describe the solution you'd like
Description of the solution: I would like to integrate the fzf.nvim plugin into the nvimDev distribution. This will allow users to invoke a fuzzy finder with a simple key combination (e.g., <leader> + ff) to quickly search for and open files. Additionally, it should support searching for content within files with a different key combination (e.g., <leader> + fg).
Describe alternatives you've considered
Description of alternatives: One alternative solution I considered was using built-in Neovim commands for file navigation, but they are often slower and less user-friendly than a dedicated fuzzy finder. Another option was to use a different fuzzy finder plugin, but fzf.nvim is well-maintained and widely used in the community.
Additional context
Context: Integrating fzf.nvim will significantly enhance the usability of nvimDev, especially for users working on large projects. By providing a smoother and more intuitive file navigation experience, we can improve overall productivity and satisfaction with the editor.

**Comment by sv410** [comment]
pls add GSSOC, hacktoberfest and level. want to work on this to enchases to the better version

**Comment by prrockzed** [comment]
But i alread have telescope, what new does fzf has, and does that help the user in real time?

**Comment by prrockzed** [comment]
Since i have telescope, i would prefer that.

Btw, I ain't telling your comment is gpt generated, but it seems like that🙃.

**Comment by sv410** [comment]
I can promise this isn’t AI-generated! Just sharing my passion about the concept. thank you for sharing your views and would like do some changes to enhance your code in future!

**Comment by prrockzed** [comment]
Ah Ok. No problem. I just wrote what i felt, my bad. Your explanation was quite good actually👍.
Sure, am open to any suggestion and feedback.
