### ISSUE TITLE
Auto Commenting on New issue Creation

### ISSUE THREAD

**Issue by sejals23** [prrockzed/nvimDev#17]
It ensures that comments on issues follow a consistent format or structure. This helps teams maintain a standardized approach to handling issues, reducing confusion and misunderstandings.
Users don’t need to manually add repetitive information or instructions. The automatic comment can include standard guidelines, troubleshooting steps, or links to documentation.

**Comment by prrockzed** [comment]
Am sorry Sejal, but this issue has been taken by another contributor before you. You can add other plugins here, if you want. There are tons of neovim plugins out there.

**Comment by prrockzed** [comment]
I don't think i need this function right now in my project.
