### ISSUE TITLE
Run Installation Test and Update Docs

### ISSUE THREAD

**Issue by prrockzed** [prrockzed/nvimDev#2]
### In Install.md:

- Curl installation for releases build(both .zip and .tar.gz) - should include unpacking them and moving them to the nvim folder
- Uninstall(For MacOS and Linux) - Checkout astrovim and nvchad and lunarvim

Check if all the commands are running fine!

### In Readme:

Include a section of "Custom Configuration" in the Readme
Here mention how a user can have a custom configuration, like they should create a folder inside lua and update the entrance level init.lua file to take effect.

**Comment by AHSANATIQ98** [comment]
"I'd like to work on this issue. Could you please assign it to me?

**Comment by prrockzed** [comment]
Sure @AHSANATIQ98 . If you have any queries related to anything, ask me here.
