### ISSUE TITLE
add readme.md file

### ISSUE THREAD

**Issue by INam1995** [prrockzed/nvimDev#24]
hey @prrockzed 

Issue: Add README.md File

We need to create a comprehensive README.md file to help new contributors and users understand the purpose of the project and how to get started.

Tasks:

Create a README.md file in the root directory of the project.
Include the following sections:
Project Overview: Briefly describe the purpose and goals of project.
Getting Started: Steps on how to clone the repo, install dependencies, and run the project.
Features: List the key features of the project.
Contributing: Basic guidelines on how others can contribute to the project.
License: Specify the license used (if applicable).
Ensure the instructions are clear and concise for new developers and users.
Submit a pull request once completed.

A clear README will help users and developers engage with the project more effectively!

**Comment by prrockzed** [comment]
Who's we? Do you consider yourself a part of this project? For that one goes through the project first, before commenting(or rather spamming).

**Comment by prrockzed** [comment]
Please close your other issues as well. They are completed too.
