### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by Hemraj-7** [prrockzed/nvimDev#26]
I want design a workflow which will greet user on their email and in the issue raising chat for raising a issue or PR

like this

![Screenshot 2024-10-17 154129](https://github.com/user-attachments/assets/7b530a7c-70d8-4d4f-a8ac-0b74a4c35844)

![Screenshot 2024-10-17 153847](https://github.com/user-attachments/assets/c6e29a6a-a29d-4d9f-9739-d79da360248e)

**Comment by Hemraj-7** [comment]
I want to work on this 
assign me

**Comment by prrockzed** [comment]
I don't have the need for this feature right now in my project.
