### ISSUE TITLE
Implement GitHub PR Issue Checker Workflow

### ISSUE THREAD

**Issue by smog-root** [prrockzed/nvimDev#28]
**Description:** We need to create a GitHub Actions workflow that automates the validation of pull requests (PRs). This workflow will ensure that all PRs meet the following criteria before being merged:

**PR Description Check:** Every PR must have a description. If the description is missing, the PR should fail the check.
    
**Issue Reference Check:** The PR description must include an issue reference in the format Fixes #<issue-number>. If the PR is not addressing an existing issue, it should mention Fixes #NEW as a placeholder.

**Acceptance Criteria:**

- A GitHub Action workflow is triggered on PR events (opened, edited).

**The workflow checks the PR body for:**
- A non-empty description.
- The presence of Fixes #<issue-number> or Fixes #NEW.

**If the criteria are not met:**

- The workflow should fail and return clear error messages.

**If the checks pass:**
- A confirmation message is outputted.

**Expected Output:**

- Error message if the PR description is missing.
- Error message if the issue reference is missing or incorrectly formatted.
- Success message when all checks are satisfied.

**Additional Notes:**

- This issue may serve as a foundation for more advanced PR validation (e.g., commit message format, label enforcement).
- We can later extend this to check for specific branch naming conventions or enforce the addition of specific labels.

_**Note**_: i'm expecting a gssoc-ext with level3 (or) level2 and a hacktoberfest-accepted label!

@prrockzed

**Comment by prrockzed** [comment]
You are expecting a level 3? Please go through your issue again, and then tell me which level are you expecting.
Also you sure you have written this issue yourself? Give an honest answer.
And have you gone through the project? People who have gone through the project, only they should contribute imo.

I will assign you the issuue, once i am thorough with your understanding. Please answer all 3 qusetions.

**Comment by prrockzed** [comment]
I mean for addition of a workflow...which literally won't do **any changes** to my project, people are asking(or rather expecting) for a Level 3 tag. I would have liked to say **any major changes**, but in this case it isn't doing any change at all. 
I guess you have mistaken Level 1 with Level 3.

**Comment by smog-root** [comment]
I have contributed to other projects on this issues!! 

Refrence:- 

https://github.com/Harshdev098/Research-Nexas/pull/275

https://github.com/SurajPratap10/Imagine_AI/pull/1304

One of the PA gave level3 and one gave level3!

@prrockzed

**Comment by smog-root** [comment]
I'm expecting level2 or a level3!!

**Comment by prrockzed** [comment]
Ok that was more than 4 lines!! I was expecting 4 answers.

Also i am going to ask about this in our PA channel in discord about this and thanks for highlighting those projects. I would take them as reference.

**Comment by prrockzed** [comment]
Also one more question, answer with yes or no.
Will your pull request, do **any kind of changes** in my project?

**Comment by smog-root** [comment]
No.

**Comment by prrockzed** [comment]
> Ok that was more than 4 lines!! I was expecting 4 answers.
> 
> Also i am going to ask about this in our PA channel in discord about this and thanks for highlighting those projects. I would take them as reference.

..

Thanks for the response.
U planning to give rest of the 3 answers?

**Comment by smog-root** [comment]
Yes. Wait I'm joining the channel!!

**Comment by smog-root** [comment]
Can I get the discord link??

**Comment by prrockzed** [comment]
> 1. You are expecting a level 3? Please go through your issue again, and then tell me which level are you expecting.
> 2. Also you sure you have written this issue yourself? Give an honest answer.
> 3. I saw your addressing term as 'we', hence i ask, have you gone through the project? People who have gone through the project, only they should contribute imo. Tell me about the project, if you gone through it.
> 4. Don't you think many of your points(assuming you have written it yourself) are repeated in the same issue for it to look big?
> 
> I will assign you the issuue, once i am thorough with your understanding. Please answer all 4 qusetions.

Actually i was asking about these qusetions. I asked 4 and you replied to only 1 of them. Do answer all!!

Also i am having a conversation about this in the project admins channel with the Program Manager. And contributors(including you) are not allowed to view the PA channel. Once confirmed it is a level 3 tag, i will give you the level3 tag. But if the program manager says it is a level 1, then i am afraid your other 2 contributions listed here, might as well get converted to a level 1 tag(if you have only done this change and nothing else).

But sure, you can have the discord link: https://discord.com/invite/nxBmE5z9Eh
I guess this is it, otherwise you can contact the GSSoC people directly from their website.

**Comment by smog-root** [comment]
Okay I can do it for any level!!!

**Comment by smog-root** [comment]
The end that matters is just contributions!!

Not points!! @prrockzed

**Comment by prrockzed** [comment]
Sure, i totally agree.
I am just checking with the program manager. I won't gain or loose anything by assigning you a tag. But just to be fair with the other contributors. Now it depends on the Program Manager, which tag he will choose for the issue. I am currently waiting for his response.

Rest assured, i will assign you the issue as you are so keen on contributing.

**Comment by prrockzed** [comment]
I had a good conversation with the Program Manager...but i will only share the ss which is relevant to this project. For the other issues, the Manager has said he will look into it. Btw, did you write this issue yourself? Do answer this question!

<img width="1093" alt="Screenshot 2024-10-22 at 1 24 17 PM" src="https://github.com/user-attachments/assets/19c79798-db7e-485f-a9e9-7aa023aa6375">

On a side note, he said he knows you from other conversations too.

**Comment by prrockzed** [comment]
I have given the labels. But i will assign you the issue, once you answer the question: Have you written this issue yourself?

**Comment by smog-root** [comment]
Yaa. I have written this issues my self!

And I copy paste the same issue with in other repos!! Some repos gave level3 some gave level2!

It' s  a strategic move!! 

Just make a issue on a topic and implement it on every repo! You can get assigned to half of the issue!! 😁

**Comment by smog-root** [comment]
> I had a good conversation with the Program Manager...but i will only share the ss which is relevant to this project. For the other issues, the Manager has said he will look into it. Btw, did you write this issue yourself? Do answer this question!
> 
> <img width="1093" alt="Screenshot 2024-10-22 at 1 24 17 PM" src="https://github.com/user-attachments/assets/19c79798-db7e-485f-a9e9-7aa023aa6375">
> 
> On a side note, he said he knows you from other conversations too.

As he said! I can add 3 workflows!! Will you do it level2??

**Comment by MastanSayyad** [comment]
Hi @smog-root,

I’ve already informed you not to raise more workflow issues, and what I said above is applies only to unique contributors. You already have **30+ merged PRs for workflows alone**, which is excessive. Have you participated in GSSoC only for workflows?

You need to contribute something more impactful for the website or projects, not just for repository workflows. Also, you mentioned, **"I copy-paste the same issue in other repos! Some repos gave level 3, some gave level 2! It’s a strategic move!"**

While it may be a strategic move, it only looks good when done less. Workflow improvements are for repository actions, not for website development. your contributions should focus more on the website developments

![image](https://github.com/user-attachments/assets/4c77d1b8-8003-40fd-8b2c-f5cd25b71523)

**Comment by smog-root** [comment]
Okay I got you point!!

I have done some website development too! 

I'm work on it too! I will make sure to do more impactful PR form now on!!

Just saying: I was just expecting to get level3 or level2 for 4 workflows.

As you said for workflows. I can get only 2 or 1. I will remember it!!

@MastanSayyad

**Comment by prrockzed** [comment]
> > I had a good conversation with the Program Manager...but i will only share the ss which is relevant to this project. For the other issues, the Manager has said he will look into it. Btw, did you write this issue yourself? Do answer this question!
> > <img alt="Screenshot 2024-10-22 at 1 24 17 PM" width="1093" src="https://private-user-images.githubusercontent.com/97661506/378737823-19c79798-db7e-485f-a9e9-7aa023aa6375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODc3MTIsIm5iZiI6MTcyOTU4NzQxMiwicGF0aCI6Ii85NzY2MTUwNi8zNzg3Mzc4MjMtMTljNzk3OTgtZGI3ZS00ODVmLWE5ZTktN2FhMDIzYWE2Mzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA4NTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NzhhMWViN2RjZGUzODAxNTVlNTVhNzdkNzJjYTQxNGY4YzYxODg1NWJjOWY2NjMxN2RjMzRhNDg3ODgzZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bua2LW2JKFykIisX6u1nb1xqFoeJt6Hq1PfxTZjftRc">
> > On a side note, he said he knows you from other conversations too.
> 
> As he said! I can add 4 workflows!! Will you do it level2??
> 
> 1. Auto comment on issue **Closed** and **Opened**
> 2. Auto comment on **PR mergs**
> 3. Auto comment on **PR raises**
> 4. (This PR)!!

No more workflows. Actually i have denied these workflow(points 1,2 and 3) contributions to previous contributors. Hence i can't assign you these. Neither do i need any of these workflows you mentioned.

Do a proper contribution once to rightly gain your level 3 tag.
As for my project, you can get a level 2 tag for adding 3 plugins(if you know what they are) to my distribution.

**Comment by prrockzed** [comment]
R u working on the issue?

**Comment by smog-root** [comment]
> R u working on the issue?

No. I will close it!! Now. 

I stopped working on workflows.. as mod suggested me!! @MastanSayyad
