### ISSUE TITLE
update nightly_git.lua

### ISSUE THREAD

**Issue by Charvi-14** [prrockzed/nvimDev#30]
1. Error Handling Enhancements:
Non-zero Git Exit Codes: Currently, exit codes are used, but more specific error messages could be given depending on the failure mode (e.g., network issues, conflicts during a pull).
Error Handling in jobstart: You can add handling for cases where the jobstart itself fails to launch or run a Git command. Right now, you’re handling failures only in the command results.
2. Code Readability and Modularity:
Separate Git Commands into Functions: You could refactor the git pull, git add, and git commit steps into individual functions to improve readability and allow for easier maintenance.
Simplify Callbacks: Using nested callbacks can get tricky. You could use a task queue or a promise-like structure to manage async Git tasks in sequence.
3. User Experience Enhancements:
Abort on Failure: After notifying the user about a failed Git operation (e.g., pull or commit failure), the script should offer an option to retry or cancel further actions rather than silently failing.
Customizable Auto-Commit Messages: Allow the user to define a default auto-commit message instead of hardcoding "Auto-commit: Staging changes before rebase".
4. Git Status Handling Improvements:
Distinguish between Untracked and Staged Changes: The current implementation doesn’t distinguish between various types of changes (modified, staged, untracked). Use git status --porcelain output to provide more nuanced feedback, like "Untracked files detected" or "Staged but not committed changes".

**Comment by prrockzed** [comment]
Ok. Go ahead. Remember to test this feature/update thoroughly. Not a single mistake should be there, when using the :NvimdevUpdateNightly command. If i am satisfied with your work, then i have another similar level 3 issue for you.

**Comment by Charvi-14** [comment]
Sure
Will start working on it
