### ISSUE TITLE
Add CONTRIBUTION.md File for Contribution Guidelines

### ISSUE THREAD

**Issue by a-n-u-vanguri** [prrockzed/nvimDev#31]
Description:

Currently, there are no specific contribution guidelines documented in a separate CONTRIBUTION.md file. This can cause confusion for new contributors on how to properly contribute to the project. The addition of a CONTRIBUTION.md file will help standardize contributions and ensure that everyone follows the same process.

Expected Changes:

Create a CONTRIBUTION.md file in the root directory of the project.
Include clear guidelines for contributing to the repository, such as:
Steps for forking the repo and making changes.
How to create and submit a pull request.
Guidelines for writing commits and pull request descriptions.
Coding standards (formatting, best practices).
How to report issues or feature requests.
Reference to the Code of Conduct.
Additional Context:

This will help streamline the contribution process, making it easier for contributors to understand the expectations and follow the correct procedure.

Thank you :)

**Comment by prrockzed** [comment]
You stated, a contributing.md file will help 'new contributors' to properly contribute to the project. Do you consider yourself a new contributor or an experienced one?

**Comment by a-n-u-vanguri** [comment]
As a new contributor, I see the value in a CONTRIBUTING.md file for gaining knowledge about the project. It offers guidelines on the contribution process, coding standards, and best practices, which can help me understand how to effectively contribute and integrate into the project. This resource is essential for building my skills and ensuring that my contributions align with the project’s goals.

**Comment by prrockzed** [comment]
Ok. So you are a new contributor. I highly doubt that your reply wasn't AI generated. Was it?

Also what do you know about the project? I generally don't assign issues to people who don't know about the project. Open source is all about contributing and knowing about the project. Treating the project as ones own.

**Comment by a-n-u-vanguri** [comment]
Absolutely, you're right! I apologize, my previous response was indeed AI-generated.

I understand your point about project knowledge. While I'm familiar with Vim and Neovim in general, I'm still learning the codebase.I'm currently working on the contribution.md to create a resource for new contributors like myself. Regardless of whether you assign me an issue, I appreciate your guidance!

**Comment by prrockzed** [comment]
And i really appreciate your truthfulness!
Not many people say this.

So, i won't take this too far as you are truthful(could have delayed the message by asking questions about my project and telling you to read the readme - as i know you haven't read it).

I already have a Contributing.md page in the .github folder.

Though i am no one to give an advice to you, but since you raised an issue regarding this, here's my 2 cents:
Always read the Readme of the project before contributing or raising any type of issue(as for my project, a contributing link is given on the 2nd line of readme).
<img width="943" alt="Screenshot 2024-10-23 at 5 20 52 PM" src="https://github.com/user-attachments/assets/948529e0-42d7-4e2a-8e14-83bde8eae9c6">

**Comment by a-n-u-vanguri** [comment]
Thanks for your suggestion .I have to be thankful for your valuable time . Since you already have a Contributing.md, that's fantastic! I'd love to help improve the Contributing.md by adding new features to it . Can you assign to work on it ? So that I can make it better.

**Comment by prrockzed** [comment]
I think the file doesn't need any updates.
But go ahead, first i want to know exactly which features are you talking about.

**Comment by a-n-u-vanguri** [comment]
Wanted to do the following changes :-

- [ ] Enhance the project structure
- [ ]  Add project structure section
- [ ]  Add additional method of contributing through GitHub desktop section
- [ ]  Add good coding practices section
- [ ]  Add the help and support section
- [ ]  Add the pull request section
- [ ]  Add issue report process section

 I think the above featured would improve  contributing.md looks to be a structured manner

**Comment by a-n-u-vanguri** [comment]
That's ok . No Worries ! . All the best for your future projects.

**Comment by prrockzed** [comment]
Thanks. Same to you too!
Keep contributing🙂
