### ISSUE TITLE
Help with Understanding Project Plugin Structure and Adding Features.

### ISSUE THREAD

**Issue by ashish-kus** [prrockzed/nvimDev#35]
Hi! I’m new to Nvim and very interested in contributing to this project. I’m looking to add a few new functionalities, but I’m still figuring out how plugins work in Neovim. I noticed that the structure of this project is a bit different from others I’ve seen, and I’m wondering if there’s any documentation or specific files you’d recommend for understanding its structure and functionality.

Could someone point me to any resources or key parts of the codebase to help me get started? Any guidance would be greatly appreciated!

**Comment by prrockzed** [comment]
Ok. Glad to hear that.
I will explain everything to you.
It's just that this isn't an issue that we will discuss here. Do read the readme and the 'Getting Started' section in it. Though it is explained in detail, if you have any questions,I would be more than happy to guide you in the Discussion Forum mentioned in the readme. Start a new discussion in the forum to discuss these things.

Right now i am closing this issue as this isn't an issue(related to the project) to begin with.
