### ISSUE TITLE
Add a "How to Contribute" Section in README.md 

### ISSUE THREAD

**Issue by Snehshishdutta** [prrockzed/nvimDev#36]
Suggestion to Add a "How to Contribute" Section in README.md

I think a "How to Contribute" section in the README.md file would be a great addition. This section could provide new contributors with a clear guide on how to get involved, including steps like:

1.Setting up the project locally
2.Finding good first issues
3.Coding standards or style guidelines
4.Creating pull requests

Adding these details could make it easier for new contributors to get started and increase overall contributions to the project. Can u assign this issue to me under gssoc-extd ,level and  hacktoberfest label?

**Comment by prrockzed** [comment]
I generally assign issues to people who have at least read the readme of the project. They should have a basic understanding of the project.

Have u read the readme?

**Comment by Snehshishdutta** [comment]
Yes i have read the Readme . nvimDev is a  sleek, fast, and customizable Neovim setup focused on simplicity, performance, and ease of use for both beginners and pros.But didn't noticed the note sorry for that.
