### ISSUE TITLE
Add code of Conduct file.

### ISSUE THREAD

**Issue by Deepika14145** [prrockzed/nvimDev#5]
Adding a Code of Conduct ensures a safe, respectful, and inclusive environment for all participants.

Here are the important Benefits of Code of Conduct: 

1) Promote inclusivity: Ensure everyone, regardless of background, feels welcome.
2) Set behavior standards: Outline acceptable and unacceptable behavior during the event.
3) Foster respect: Encourage mutual respect, collaboration, and support among participants.
4) Ensure safety: Provide mechanisms for reporting and addressing misconduct or harassment.

![Screenshot 2024-10-04 235524](https://github.com/user-attachments/assets/2efe4879-decb-49b1-a425-750ff8eb84fa)

Please assign me this task @prrockzed, @AHSANATIQ98, I will give my best. 

Also, add labels GSSoC-Extd | Hactoberfest-accepted | Labels as per your convenience.

**Comment by prrockzed** [comment]
Before creating an issue, please check if the issue actually persists. The 'Code of Conduct'  button is right beside the Readme file if you are looking at the desktop version of Github. As for the location of the file it is in the .github file. Hence, I see no issue here, so closing the issue. If want to contribute in anyway else, create a separate issue for that.
Thanks

**Comment by Deepika14145** [comment]
Thank You for the clarification regarding its location.
