### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [prrockzed/nvimDev#6]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by prrockzed** [comment]
Ok, go ahead. Make sure to add 'Contributors' in the content section of the readme as well and keep the contributors just before the support section.

**Comment by Shariq2003** [comment]
sure @prrockzed

**Comment by Shariq2003** [comment]
@prrockzed please mark this as completed in #7
